echo "Setting up environment variables ..."

export NODEJS_OTEL_LAYER_REGION="eu-west-1"
export NODEJS_OTEL_LAYER_NAME_VERSION="1-0-0"
export NODEJS_OTEL_LAYER_VERSION="1"

export PHYTON_OTEL_LAYER_REGION="eu-west-1"
export PHYTON_OTEL_LAYER_NAME_VERSION="1-7-1"
export PHYTON_OTEL_LAYER_VERSION="1"

export JAVA_OTEL_LAYER_REGION="eu-west-1"
export JAVA_OTEL_LAYER_NAME_VERSION="1-7-0"
export JAVA_OTEL_LAYER_VERSION="1"

export DOTNET_OTEL_LAYER_REGION="eu-west-1"
export DOTNET_OTEL_LAYER_NAME_VERSION="0-39-0"
export DOTNET_OTEL_LAYER_VERSION="1"

export GOLANG_OTEL_LAYER_REGION="eu-west-1"
export GOLANG_OTEL_LAYER_NAME_VERSION="0-39-0"
export GOLANG_OTEL_LAYER_VERSION="1"
